import { useMemo, useState } from "react";
import { Link } from "wouter";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { AIChatBox, type Message } from "@/components/AIChatBox";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { toast } from "sonner";
import {
  ArrowRight, Cable, Check, ChevronDown, CircleHelp, Factory, FileText, Headphones, Menu, PackageSearch, PlugZap, Quote, ShieldCheck, Sparkles, Truck, UserRound, X, Zap,
} from "lucide-react";

type Product = { name: string; category: string; detail: string; accent: "orange" | "brown" | "yellow"; icon: typeof Cable; price: number; unit: string; use: string };

const products: Product[] = [
  { name: "LV Power Cable", category: "Power cables", detail: "Low-voltage cable options for dependable building and plant distribution.", accent: "brown", icon: Cable, price: 118, unit: "per metre", use: "Buildings, plants and distribution panels" },
  { name: "Instrumentation Cable", category: "Industrial systems", detail: "Shielded signal cabling for control rooms and process environments.", accent: "orange", icon: Factory, price: 142, unit: "per metre", use: "Instrumentation and industrial automation" },
  { name: "Solar Cable", category: "Renewable & EV", detail: "Purpose-built cable for solar installations and renewable-energy systems.", accent: "yellow", icon: Zap, price: 76, unit: "per metre", use: "Solar plants and rooftop installations" },
  { name: "Building Wire", category: "Building & wiring", detail: "Everyday wiring for residential, commercial and contractor requirements.", accent: "orange", icon: PlugZap, price: 42, unit: "per metre", use: "Homes, offices and general wiring" },
  { name: "Control & Data Cable", category: "Communication & control", detail: "Clear connections for CCTV, LAN, telephone and smart systems.", accent: "brown", icon: PlugZap, price: 68, unit: "per metre", use: "Communication and control networks" },
];

const solutions = [
  { title: "Power distribution", copy: "LV, MV and EHV cable sourcing for infrastructure that cannot pause.", icon: Cable, label: "01" },
  { title: "Industrial systems", copy: "Instrumentation, rubber, flexible and special-purpose cable requirements.", icon: Factory, label: "02" },
  { title: "Future energy", copy: "Solar and EV cable categories for the next generation of projects.", icon: Zap, label: "03" },
];

function BrandMark() {
  return <div className="brand-mark" aria-label="VOLAMP home"><img src="/manus-storage/volamp-logo-corrected_263c7f84.png" alt="VOLAMP Powering Growth" /><span className="sr-only">VOLAMP Powering Growth</span></div>;
}

function ProductIllustration({ product }: { product: Product }) {
  const Icon = product.icon;
  return <div className={`product-art art-${product.accent}`}><div className="wire-orbit" /><Icon className="relative z-10 size-14 stroke-[1.25]" /><div className="spark spark-one" /><div className="spark spark-two" /><span className="product-art-code">{product.category === "Power cables" ? "PWR" : product.category === "Industrial systems" ? "IND" : product.category === "Renewable & EV" ? "RE" : "SYS"}</span></div>;
}

export default function Home() {
  const { user } = useAuth();
  const [mobileOpen, setMobileOpen] = useState(false);
  const [chatOpen, setChatOpen] = useState(false);
  const [accountOpen, setAccountOpen] = useState(false);
  const [selectedDetail, setSelectedDetail] = useState<Product | null>(null);
  const [compareList, setCompareList] = useState<string[]>([]);
  const [quantity, setQuantity] = useState(100);
  const [selectedProduct, setSelectedProduct] = useState(products[0]);
  const [discount, setDiscount] = useState(5);
  const [messages, setMessages] = useState<Message[]>([
    { role: "system", content: "You are Vola, VOLAMP's friendly product and quotation assistant. Answer only approved questions about VOLAMP, its products, quotations, customer support, and company. If unsure, recommend human support." },
    { role: "assistant", content: "I’m Vola. Tell me what you’re building, which cable category you’re considering, or whether you want to prepare a quotation request." },
  ]);
  const chatMutation = trpc.ai.chat.useMutation({
    onSuccess: (response) => setMessages((current) => [...current, { role: "assistant", content: response }]),
    onError: () => setMessages((current) => [...current, { role: "assistant", content: "I could not complete that answer. Please use human support for a confirmed technical or commercial response." }]),
  });
  const total = useMemo(() => Math.round(quantity * selectedProduct.price * (1 - discount / 100)), [quantity, selectedProduct, discount]);
  const jump = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); setMobileOpen(false); };
  const handleSend = (content: string) => { const next = [...messages, { role: "user" as const, content }]; setMessages(next); chatMutation.mutate({ messages: next }); };
  const handleQuote = () => { jump("quote"); toast.success("Quotation desk is ready", { description: "Share your project requirement and a VOLAMP specialist will follow up." }); };
  const toggleCompare = (name: string) => setCompareList((current) => current.includes(name) ? current.filter((item) => item !== name) : current.length < 3 ? [...current, name] : current);

  return <div className="volamp-site">
    <div className="utility-bar"><div className="container utility-inner"><span><span className="status-dot" /> Ahmedabad · Gujarat · India</span><span className="utility-right">One-point sourcing for project requirements <button onClick={handleQuote}>Talk to supply desk <ArrowRight className="inline size-3" /></button></span></div></div>
    <header className="site-header"><div className="container header-inner"><a href="#top"><BrandMark /></a><nav className="desktop-nav" aria-label="Main navigation">{["Products", "Solutions", "Our history", "Resources"].map((item) => <button key={item} onClick={() => jump(item === "Products" ? "products" : item === "Solutions" ? "solutions" : item === "Our history" ? "history" : "resources")}>{item}</button>)}</nav><div className="header-actions"><button className="portal-link" onClick={() => setAccountOpen(true)}><UserRound className="size-4" /> {user ? "My portal" : "Sign in"}</button><Button onClick={handleQuote} className="header-quote">Request a quote <ArrowRight className="ml-2 size-4" /></Button></div><Button variant="ghost" size="icon" className="mobile-menu-button" aria-label="Open navigation" onClick={() => setMobileOpen(true)}><Menu /></Button></div>{mobileOpen && <div className="mobile-nav"><button className="mobile-close" onClick={() => setMobileOpen(false)} aria-label="Close navigation"><X /></button>{["Products", "Solutions", "Our history", "Resources"].map((item) => <button key={item} onClick={() => jump(item === "Products" ? "products" : item === "Solutions" ? "solutions" : item === "Our history" ? "history" : "resources")}>{item}</button>)}<button onClick={() => setAccountOpen(true)}>{user ? "Open my portal" : "Sign in"}</button></div>}</header>

    <main id="top">
      <section className="industrial-hero"><div className="container hero-grid"><div className="hero-copy"><div className="kicker"><span className="kicker-line" /> ELECTRICAL SUPPLY · EST. LEGACY 1960s</div><h1>Supply certainty<br /><em>for real work.</em></h1><p>Volamp helps contractors, industries, builders, dealers and project teams source the right cable categories with clearer specifications, dependable follow-up and one accountable supply partner.</p><div className="hero-ctas"><Button onClick={() => jump("products")} className="primary-cta">Explore cable categories <ArrowRight className="ml-2 size-4" /></Button><button onClick={() => setChatOpen(true)} className="text-cta"><Sparkles className="size-4" /> Ask Vola</button></div><div className="hero-proof"><span><ShieldCheck /> Specification clarity</span><span><Truck /> India-ready supply</span><span><Headphones /> Human escalation</span></div></div><div className="engineering-visual"><div className="visual-grid" /><div className="terminal terminal-a"><span>INPUT</span><strong>11kV</strong><small>MV FEED</small></div><div className="terminal terminal-b"><span>OUTPUT</span><strong>LV</strong><small>SAFE ROUTE</small></div><div className="circuit-path path-a" /><div className="circuit-path path-b" /><div className="circuit-node node-a" /><div className="circuit-node node-b" /><div className="circuit-label">VOLAMP / SUPPLY SYSTEMS</div><div className="visual-stamp">PWR<br /><small>READY</small></div></div></div></section>

      <section className="container metric-strip"><div><strong>1960s</strong><span>reported brand legacy</span></div><div><strong>2012</strong><span>business revival</span></div><div><strong>2021</strong><span>present entity incorporated</span></div><div><strong>2024+</strong><span>export visibility</span></div></section>

      <section id="solutions" className="section-block solutions-block"><div className="container"><div className="section-intro"><div><div className="kicker">WHAT WE SOURCE</div><h2>Built around the<br /><em>circuit of work.</em></h2></div><p>From everyday wiring to industrial and renewable-energy applications, Volamp brings multiple cable requirements into one clearer conversation.</p></div><div className="solution-grid">{solutions.map(({ title, copy, icon: Icon, label }) => <button className="solution-card" key={title} onClick={() => jump("products")}><div className="solution-top"><span>{label}</span><Icon /></div><h3>{title}</h3><p>{copy}</p><span className="solution-link">View relevant products <ArrowRight /></span></button>)}</div></div></section>

      <section id="products" className="section-block product-block"><div className="container"><div className="section-intro product-intro"><div><div className="kicker">PRODUCT CATEGORIES</div><h2>Choose the right<br /><em>connection.</em></h2></div><p>Our published portfolio spans EHV, MV and LV power cables, building wires, flexible, instrumentation, rubber, solar, EV, communication and FS cable categories.</p></div><div className="catalog-toolbar"><span>{products.length} starting categories</span><button onClick={() => toast.info("The full product catalogue is being prepared", { description: "Ask Vola or contact the supply desk for a category-specific conversation." })}>Download category guide <ArrowRight className="size-4" /></button></div><div className="product-grid">{products.map((product) => <article className="catalog-card" key={product.name}><ProductIllustration product={product} /><div className="catalog-card-body"><div className="catalog-meta"><span>{product.category}</span><button onClick={() => toggleCompare(product.name)} className={compareList.includes(product.name) ? "compare-chip active" : "compare-chip"}>{compareList.includes(product.name) ? <Check className="size-3" /> : "+"} Compare</button></div><h3>{product.name}</h3><p>{product.detail}</p><div className="catalog-footer"><span>Indicative from <strong>₹{product.price}</strong> / m</span><button className="detail-button" onClick={() => setSelectedDetail(product)}>View details <ArrowRight className="size-4" /></button></div></div></article>)}</div></div></section>

      {compareList.length > 0 && <section className="compare-section"><div className="container"><div className="compare-head"><div><div className="kicker">PROJECT SHORTLIST</div><h2>Compare <em>before you request.</em></h2></div><button className="clear-link" onClick={() => setCompareList([])}>Clear shortlist</button></div><div className="compare-table"><div className="compare-labels"><strong>Product</strong><span>Application</span><span>Unit price</span><span>Estimate at {quantity} m</span></div>{products.filter((product) => compareList.includes(product.name)).map((product) => <div className="compare-product" key={product.name}><div className="compare-product-name"><strong>{product.name}</strong><span>{product.category}</span></div><span>{product.use}</span><span>₹{product.price} / m</span><strong className="estimate-accent">₹{Math.round(quantity * product.price * (1 - discount / 100)).toLocaleString("en-IN")}</strong></div>)}</div><p className="compare-note">Indicative estimates only. Final specifications, availability, taxes, freight and commercial terms are confirmed by Volamp.</p></div></section>}

      <section id="history" className="section-block history-block"><div className="container history-grid"><div><div className="kicker">OUR HISTORY</div><h2>A long view on<br /><em>reliable supply.</em></h2><p className="history-lead">Volamp’s public story carries a reported legacy from the 1960s, a revival in 2012, and a present legal entity incorporated in Ahmedabad in 2021. We present those moments with the evidence distinction they deserve.</p><button className="text-cta" onClick={() => toast.info("Corporate history reference", { description: "Company-reported heritage and public-record milestones are intentionally distinguished." })}>Read the story <ArrowRight className="size-4" /></button></div><div className="timeline"><div className="timeline-row"><span>1960s</span><div><strong>Reported origin</strong><p>Company narrative places the beginning of the Volamp legacy during India’s electrification era.</p></div></div><div className="timeline-row"><span>2012</span><div><strong>Revival</strong><p>The business was revived around a practical gap: late deliveries, unavailable cables and unclear specifications.</p></div></div><div className="timeline-row"><span>19 MAY 2021</span><div><strong>Present legal entity</strong><p>Volamp Elektrikals Private Limited was incorporated in Ahmedabad under CIN U31900GJ2021PTC122730.</p></div></div><div className="timeline-row"><span>2024–25</span><div><strong>Export visibility</strong><p>Public trade records show Volamp-branded cable shipments to Kenya during this period.</p></div></div></div></div></section>

      <section id="calculator" className="section-block calculator-block"><div className="container calculator-layout"><div><div className="kicker">PROJECT PLANNING TOOL</div><h2>Start with a<br /><em>working estimate.</em></h2><p>Use a simple starting point for internal planning. A formal quotation always follows technical and commercial review by the supply desk.</p><div className="calculator-notes"><span><Check /> Before taxes and freight</span><span><Check /> Indicative prices only</span><span><Check /> Finalized by a human specialist</span></div></div><div className="estimate-panel"><div className="estimate-header"><div><span className="panel-label">ESTIMATE BUILDER</span><h3>Make the requirement tangible.</h3></div><CalculatorIcon /></div><div className="estimate-field"><Label>Product category</Label><div className="product-pills">{products.slice(0, 3).map((product) => <button key={product.name} onClick={() => setSelectedProduct(product)} className={selectedProduct.name === product.name ? "selected" : ""}>{product.name}</button>)}</div></div><div className="estimate-fields"><div><Label htmlFor="quantity">Quantity (metres)</Label><Input id="quantity" type="number" min="1" value={quantity} onChange={(e) => setQuantity(Math.max(1, Number(e.target.value)))} /></div><div><Label htmlFor="discount">Planning discount (%)</Label><Input id="discount" type="number" min="0" max="30" value={discount} onChange={(e) => setDiscount(Math.min(30, Math.max(0, Number(e.target.value))))} /></div></div><div className="estimate-total"><span>Starting estimate<strong>Before taxes & freight</strong></span><b>₹{total.toLocaleString("en-IN")}</b></div><Button onClick={handleQuote} className="primary-cta wide">Turn this into a quotation <Quote className="ml-2 size-4" /></Button></div></div></section>

      <section id="resources" className="section-block resource-block"><div className="container"><div className="section-intro"><div><div className="kicker">SUPPORTING THE SUPPLY CHAIN</div><h2>Clearer work.<br /><em>Fewer dead ends.</em></h2></div><p>Volamp positions itself as a supply partner: planned inventory, one-point sourcing, inquiry tracking, timely follow-up, and clear communication.</p></div><div className="resource-grid"><button onClick={() => setChatOpen(true)}><CircleHelp /><span>Ask a product question</span><small>Get a high-level answer from Vola, then escalate when required.</small><ArrowRight /></button><button onClick={handleQuote}><FileText /><span>Request a quotation</span><small>Give the supply desk the context needed to start correctly.</small><ArrowRight /></button><Link href="/portal"><PackageSearch /><span>Open customer portal</span><small>Keep quotations, orders, documents and support in one space.</small><ArrowRight /></Link></div></div></section>

      <section id="quote" className="section-block contact-block"><div className="container contact-grid"><div><div className="kicker">CONTACT THE SUPPLY DESK</div><h2>Tell us what the<br /><em>project needs.</em></h2><p>Share a requirement, a category, or a specification question. A Volamp specialist can help make the next step clear.</p><div className="contact-facts"><span><Factory /> Ahmedabad-based</span><span><Truck /> India-ready supply</span><span><Headphones /> Human follow-up</span></div></div><div className="inquiry-panel"><span className="panel-label">START AN INQUIRY</span><h3>Let’s work from the requirement.</h3><Input placeholder="Your name" aria-label="Your name" /><Input placeholder="Work email or phone" aria-label="Work email or phone" /><Input placeholder="What are you sourcing?" aria-label="What are you sourcing" /><Button onClick={() => toast.success("Inquiry noted", { description: "Connect the form to your sales workflow when your enquiry endpoint is ready." })} className="primary-cta wide">Send inquiry <ArrowRight className="ml-2 size-4" /></Button></div></div></section>

      <section className="container final-banner"><div><div className="kicker">VOLAMP ELEKTRIKALS PVT. LTD.</div><h2>Supply that respects<br /><em>the work.</em></h2></div><Button onClick={handleQuote} className="primary-cta">Request a project conversation <ArrowRight className="ml-2 size-4" /></Button></section>
    </main>

    <footer className="site-footer"><div className="container footer-grid"><BrandMark /><div><span>EXPLORE</span><button onClick={() => jump("products")}>Product categories</button><button onClick={() => jump("solutions")}>Solutions</button></div><div><span>CUSTOMER</span><Link href="/portal">Customer portal</Link><button onClick={handleQuote}>Request a quotation</button></div><div><span>COMPANY</span><button onClick={() => jump("history")}>Our history</button><button onClick={() => setChatOpen(true)}>Ask Vola</button></div></div><div className="container footer-bottom"><span>© 2026 Volamp Elektrikals Private Limited. Content is presented for customer information.</span><span>Built for clearer electrical sourcing.</span></div></footer>

    {selectedDetail && <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label={`${selectedDetail.name} details`} onClick={() => setSelectedDetail(null)}><div className="product-modal" onClick={(e) => e.stopPropagation()}><button className="modal-close" onClick={() => setSelectedDetail(null)} aria-label="Close details"><X /></button><ProductIllustration product={selectedDetail} /><div className="kicker">{selectedDetail.category}</div><h2>{selectedDetail.name}</h2><p>{selectedDetail.detail}</p><div className="modal-application"><strong>Typical application</strong><span>{selectedDetail.use}</span></div><Button onClick={handleQuote} className="primary-cta wide">Request this category <ArrowRight className="ml-2 size-4" /></Button></div></div>}
    {accountOpen && <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="Volamp account access" onClick={() => setAccountOpen(false)}><div className="account-modal" onClick={(e) => e.stopPropagation()}><button className="modal-close" onClick={() => setAccountOpen(false)} aria-label="Close account access"><X /></button><div className="account-icon"><UserRound /></div><div className="kicker">ACCOUNT ACCESS</div><h2>{user ? "Your customer workspace." : "Keep your project moving."}</h2><p>{user ? "Open your private portal for quotations, orders, documents and support." : "Sign in or create an account to keep your customer information and project requests together."}</p>{user ? <Link href="/portal" onClick={() => setAccountOpen(false)}><Button className="primary-cta wide">Open customer portal <ArrowRight className="ml-2 size-4" /></Button></Link> : <Button onClick={startLogin} className="primary-cta wide">Sign in or create account <ArrowRight className="ml-2 size-4" /></Button>}<button className="employee-access" onClick={startLogin}>Employee signup / login <ArrowRight className="size-4" /></button></div></div>}
    {chatOpen && <div className="chat-drawer"><div className="chat-drawer-head"><div><span className="panel-label">VOLAMP AI ASSISTANT</span><strong>Vola is online</strong></div><button onClick={() => setChatOpen(false)} aria-label="Close assistant"><X /></button></div><AIChatBox messages={messages} onSendMessage={handleSend} isLoading={chatMutation.isPending} height="calc(100vh - 110px)" placeholder="Ask about products or a quotation..." suggestedPrompts={["Which cable category fits industrial control?", "How do I request a quotation?", "Connect me with human support"]} /></div>}
  </div>;
}

function CalculatorIcon() { return <div className="calculator-icon"><Zap className="size-5" /></div>; }
