import { useMemo, useState } from "react";
import { Link } from "wouter";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { AIChatBox, type Message } from "@/components/AIChatBox";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { toast } from "sonner";
import {
  ArrowRight,
  Calculator,
  Cable,
  Check,
  ChevronDown,
  CircleHelp,
  FileText,
  Headphones,
  Menu,
  PackageSearch,
  PlugZap,
  Quote,
  ShieldCheck,
  Sparkles,
  Truck,
  UserRound,
  X,
  Zap,
} from "lucide-react";

const products = [
  { name: "PowerFlex FR Cable", category: "House wires", detail: "Flame-retardant copper cable for safer everyday power.", accent: "orange", icon: Cable, price: 42, unit: "per metre" },
  { name: "VoltGuard XL", category: "Industrial cables", detail: "Durable low-voltage cable made for demanding projects.", accent: "brown", icon: Zap, price: 118, unit: "per metre" },
  { name: "SparkLink Control", category: "Control & data", detail: "Clean, dependable signal cabling for smart systems.", accent: "yellow", icon: PlugZap, price: 76, unit: "per metre" },
];

const categories = [
  { title: "House wires", copy: "Bright, dependable power for every room.", icon: PlugZap, tone: "bg-sun text-brown" },
  { title: "Industrial cables", copy: "Tough cable solutions that keep work moving.", icon: Cable, tone: "bg-orange text-white" },
  { title: "Control & data", copy: "Neat connections for smarter systems.", icon: Zap, tone: "bg-brown text-sun" },
];

function BrandMark({ compact = false }: { compact?: boolean }) {
  return (
    <div className="flex items-center gap-3" aria-label="VOLTAMP home">
      <img src="/manus-storage/image1_3099e136.jpeg" alt="VOLTAMP Powering Growth" className="h-11 w-[92px] object-contain object-left" />
      {!compact && <span className="sr-only">VOLTAMP Powering Growth</span>}
    </div>
  );
}

function ProductIllustration({ product }: { product: typeof products[number] }) {
  const Icon = product.icon;
  return <div className={`product-art art-${product.accent}`}><div className="wire-orbit" /><Icon className="relative z-10 size-16 stroke-[1.35]" /><div className="spark spark-one" /><div className="spark spark-two" /></div>;
}

export default function Home() {
  const { user } = useAuth();
  const [mobileOpen, setMobileOpen] = useState(false);
  const [chatOpen, setChatOpen] = useState(false);
  const [accountOpen, setAccountOpen] = useState(false);
  const [selectedDetail, setSelectedDetail] = useState<typeof products[number] | null>(null);
  const [compareList, setCompareList] = useState<string[]>([]);
  const [quantity, setQuantity] = useState(100);
  const [selectedProduct, setSelectedProduct] = useState(products[0]);
  const [discount, setDiscount] = useState(5);
  const [messages, setMessages] = useState<Message[]>([
    { role: "system", content: "You are Volt, VOLTAMP's friendly product and quotation assistant. Answer only approved questions about VOLTAMP, its products, quotations, customer support, and company. If unsure, recommend human support." },
    { role: "assistant", content: "Hi, I’m Volt. I can help you find the right cable, understand a product, or start a quotation. What are you working on?" },
  ]);
  const chatMutation = trpc.ai.chat.useMutation({
    onSuccess: (response) => setMessages((current) => [...current, { role: "assistant", content: response }]),
    onError: () => setMessages((current) => [...current, { role: "assistant", content: "I’m having a tiny connection hiccup. Please use the human support option and our team will take it from here." }]),
  });
  const total = useMemo(() => Math.round(quantity * selectedProduct.price * (1 - discount / 100)), [quantity, selectedProduct, discount]);

  const nav = ["Products", "Solutions", "About us", "Resources"];
  const jump = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); setMobileOpen(false); };
  const handleSend = (content: string) => { const next = [...messages, { role: "user" as const, content }]; setMessages(next); chatMutation.mutate({ messages: next }); };
  const handleQuote = () => toast.success("Quotation desk is ready", { description: "Tell us what you need and a VOLTAMP specialist will get in touch." });
  const toggleCompare = (name: string) => setCompareList((current) => current.includes(name) ? current.filter((item) => item !== name) : current.length < 3 ? [...current, name] : current);

  return (
    <div className="min-h-screen overflow-x-hidden bg-cream text-brown">
      <div className="announcement"><span className="inline-flex items-center gap-2"><Sparkles className="size-4" /> Friendly power, made for progress.</span><button onClick={() => jump("quote")} className="font-bold underline underline-offset-4">Start a project <ArrowRight className="ml-1 inline size-4" /></button></div>
      <header className="sticky top-0 z-40 border-b border-brown/10 bg-cream/95 backdrop-blur">
        <div className="container flex h-20 items-center justify-between gap-6">
          <a href="#top" className="shrink-0"><BrandMark /></a>
          <nav className="hidden items-center gap-8 text-sm font-bold md:flex">{nav.map((item) => <button key={item} onClick={() => jump(item === "Products" ? "products" : item === "About us" ? "about" : item === "Resources" ? "resources" : "calculator")} className="nav-link">{item}</button>)}</nav>
          <div className="hidden items-center gap-3 md:flex"><button className="account-button" onClick={() => setAccountOpen(true)}><UserRound className="size-4" /> {user ? "My portal" : "Sign in"}</button><Button onClick={handleQuote} className="rounded-full bg-brown px-5 text-white shadow-[0_6px_0_#e7a91a] hover:bg-brown/90">Request a quote <ArrowRight className="ml-2 size-4" /></Button></div>
          <div className="flex items-center gap-2 md:hidden"><Button variant="ghost" size="icon" aria-label="Open menu" onClick={() => setMobileOpen(true)}><Menu /></Button></div>
        </div>
      </header>

      <main id="top">
        <section className="hero-section"><div className="container grid items-center gap-12 py-16 lg:grid-cols-[1.03fr_.97fr] lg:py-24"><div className="relative z-10"><Badge className="mb-6 rounded-full border-0 bg-sun px-4 py-2 text-[11px] font-black uppercase tracking-[0.18em] text-brown">Powering India, one bright idea at a time</Badge><h1 className="max-w-3xl font-display text-5xl font-black leading-[.94] tracking-[-0.06em] sm:text-7xl">Good energy<br /><span className="text-orange">starts here.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-brown/75">Cables and electrical essentials that make projects feel simpler, safer, and a little more joyful. Meet your friendly power partner from Ahmedabad.</p><div className="mt-9 flex flex-wrap gap-3"><Button onClick={() => jump("products")} className="rounded-full bg-orange px-6 py-6 text-base font-black text-white shadow-[0_7px_0_#6b2024] hover:bg-orange/90">Explore products <ArrowRight className="ml-2 size-5" /></Button><Button variant="outline" onClick={() => setChatOpen(true)} className="rounded-full border-2 border-brown bg-transparent px-6 py-6 text-base font-black text-brown hover:bg-sun"><Sparkles className="mr-2 size-5" /> Ask Volt</Button></div><div className="mt-10 flex flex-wrap gap-x-7 gap-y-3 text-sm font-bold"><span className="inline-flex items-center gap-2"><ShieldCheck className="size-5 text-orange" /> Quality-minded</span><span className="inline-flex items-center gap-2"><Truck className="size-5 text-orange" /> India-ready delivery</span></div></div><div className="hero-visual"><div className="blob blob-one" /><div className="blob blob-two" /><div className="hero-cable"><div className="cable-head"><div className="cable-pin" /></div><div className="cable-line" /><div className="cable-bend" /></div><div className="hero-note note-one"><span>01</span><strong>Reliable</strong><small>for real work</small></div><div className="hero-note note-two"><span>02</span><strong>Friendly</strong><small>by design</small></div><div className="hero-caption">VOLTAMP<br /><span>Powering growth</span></div></div></div></section>

        <section className="container -mt-2 pb-16"><div className="stats-card"><div><strong>15+</strong><span>years of know-how</span></div><div><strong>3</strong><span>power essentials</span></div><div><strong>1</strong><span>helpful human team</span></div><div><strong>24/7</strong><span>ideas welcome</span></div></div></section>

        <section id="products" className="section-space"><div className="container"><div className="section-heading"><div><p className="eyebrow">Find your fit</p><h2>Products with a little <span>spark.</span></h2></div><button onClick={() => toast.info("Full catalog is being prepared", { description: "The first customer-board release starts with these core product families." })} className="text-link">View all products <ArrowRight className="size-4" /></button></div><div className="grid gap-5 md:grid-cols-3">{categories.map(({ title, copy, icon: Icon, tone }) => <button key={title} onClick={() => setSelectedProduct(products.find((p) => p.category === title) ?? products[0])} className={`category-card ${tone}`}><div className="flex items-start justify-between"><div className="icon-disc"><Icon className="size-7" /></div><ArrowRight className="size-5" /></div><div className="mt-16 text-left"><h3>{title}</h3><p>{copy}</p></div></button>)}</div><div className="mt-9 grid gap-5 lg:grid-cols-3">{products.map((product) => <Card key={product.name} className="product-card"><CardContent className="p-4"><ProductIllustration product={product} /><div className="px-2 pb-2 pt-5"><p className="text-xs font-black uppercase tracking-[.16em] text-orange">{product.category}</p><h3 className="mt-2 font-display text-2xl font-black">{product.name}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-brown/70">{product.detail}</p><div className="mt-5 flex items-center justify-between gap-2"><span className="font-black">₹{product.price} <small className="font-medium text-brown/50">{product.unit}</small></span><div className="flex items-center gap-2"><button onClick={() => toggleCompare(product.name)} className={`compare-toggle ${compareList.includes(product.name) ? "active" : ""}`} aria-label={`${compareList.includes(product.name) ? "Remove" : "Add"} ${product.name} ${compareList.includes(product.name) ? "from" : "to"} comparison`}>{compareList.includes(product.name) ? <Check className="size-3" /> : "+"} Compare</button><button className="round-arrow" onClick={() => setSelectedDetail(product)} aria-label={`View details for ${product.name}`}><ArrowRight className="size-4" /></button></div></div></div></CardContent></Card>)}</div></div></section>

        {compareList.length > 0 && <section id="compare" className="compare-section"><div className="container"><div className="compare-head"><div><p className="eyebrow">Side by side</p><h2>Compare your <span>shortlist.</span></h2></div><button className="clear-link" onClick={() => setCompareList([])}>Clear all</button></div><div className="compare-table"><div className="compare-labels"><strong>Product</strong><span>Category</span><span>Unit price</span><span>Estimate at {quantity} m</span></div>{products.filter((product) => compareList.includes(product.name)).map((product) => <div className="compare-product" key={product.name}><div className="compare-product-name"><ProductIllustration product={product} /><strong>{product.name}</strong></div><span>{product.category}</span><span>₹{product.price} / m</span><strong className="text-orange">₹{Math.round(quantity * product.price * (1 - discount / 100)).toLocaleString("en-IN")}</strong></div>)}</div><p className="compare-note">Estimates use the same quantity and discount controls below and are not official quotations. Final commercial terms are validated by VOLTAMP.</p></div></section>}

        <section id="calculator" className="section-space bg-brown text-cream"><div className="container grid gap-12 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><p className="eyebrow text-sun">Plan with confidence</p><h2 className="text-cream">A quick estimate<br /><span className="text-sun">before you call.</span></h2><p className="mt-6 max-w-md text-lg leading-8 text-cream/70">Choose a product, add your quantity, and get a friendly starting point. Your final business quote is always validated by our team.</p><div className="mt-7 flex items-center gap-3 text-sm font-bold"><Calculator className="size-5 text-sun" /> Built for future GST, freight, and pricing rules</div></div><div className="calculator-card"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.15em] text-orange">Estimate builder</p><h3 className="mt-2 font-display text-2xl font-black">Let’s make it tangible.</h3></div><div className="calc-icon"><Calculator className="size-5" /></div></div><div className="mt-7 grid gap-5 sm:grid-cols-2"><div className="sm:col-span-2"><Label>Product</Label><div className="mt-2 flex flex-wrap gap-2">{products.map((p) => <button key={p.name} onClick={() => setSelectedProduct(p)} className={`choice-chip ${selectedProduct.name === p.name ? "selected" : ""}`}>{p.name}</button>)}</div></div><div><Label htmlFor="quantity">Quantity (metres)</Label><Input id="quantity" type="number" min="1" value={quantity} onChange={(e) => setQuantity(Math.max(1, Number(e.target.value)))} className="mt-2 rounded-2xl border-2 border-brown/10 bg-cream text-brown" /></div><div><Label htmlFor="discount">Discount estimate (%)</Label><Input id="discount" type="number" min="0" max="30" value={discount} onChange={(e) => setDiscount(Math.min(30, Math.max(0, Number(e.target.value))))} className="mt-2 rounded-2xl border-2 border-brown/10 bg-cream text-brown" /></div></div><div className="mt-7 flex items-end justify-between border-t-2 border-brown/10 pt-6"><div><p className="text-sm font-bold text-brown/60">Starting estimate</p><p className="mt-1 text-xs text-brown/50">Before taxes & freight</p></div><strong className="font-display text-4xl font-black text-orange">₹{total.toLocaleString("en-IN")}</strong></div><Button onClick={handleQuote} className="mt-6 w-full rounded-full bg-orange py-6 text-base font-black text-white hover:bg-orange/90">Turn this into a quotation <Quote className="ml-2 size-5" /></Button></div></div></section>

        <section id="about" className="section-space"><div className="container grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div className="about-art"><div className="about-sun" /><div className="about-card about-card-main"><Zap className="size-12 text-orange" /><p>Powering</p><strong>good work</strong></div><div className="about-card about-card-small"><Check className="size-5" /><span>Made for India</span></div></div><div><p className="eyebrow">Why VOLTAMP</p><h2>Serious about power.<br /><span>Easy to work with.</span></h2><p className="mt-6 max-w-xl text-lg leading-8 text-brown/70">We bring practical electrical expertise and a human-first way of working together. That means clear answers, considered products, and support that does not make you chase a maze of menus.</p><div className="mt-8 grid gap-5 sm:grid-cols-2"><div className="feature-line"><div className="feature-icon"><ShieldCheck /></div><div><strong>Quality-minded</strong><p>Thoughtful product information, without the jargon fog.</p></div></div><div className="feature-line"><div className="feature-icon"><Headphones /></div><div><strong>Human support</strong><p>Ask Volt, then hand the conversation to a person whenever you need.</p></div></div></div></div></div></section>

        <section id="resources" className="section-space bg-sun"><div className="container"><div className="section-heading"><div><p className="eyebrow">Helpful by default</p><h2>Make the next step feel <span>simple.</span></h2></div></div><div className="grid gap-5 md:grid-cols-3"><button onClick={() => setChatOpen(true)} className="resource-card"><div className="resource-icon"><CircleHelp /></div><h3>Ask a product question</h3><p>Get a quick, friendly answer from Volt or escalate to our team.</p><ArrowRight /></button><button onClick={handleQuote} className="resource-card"><div className="resource-icon"><FileText /></div><h3>Start a quotation</h3><p>Share your requirements and we will help shape the right request.</p><ArrowRight /></button><button onClick={() => setAccountOpen(true)} className="resource-card"><div className="resource-icon"><PackageSearch /></div><h3>Open your portal</h3><p>Keep quotations, orders, documents, and support in one place.</p><ArrowRight /></button></div></div></section>

        <section id="faq" className="section-space"><div className="container grid gap-10 lg:grid-cols-[1fr_1fr]"><div><p className="eyebrow">Helpful answers</p><h2>Questions? We keep them <span>bright.</span></h2><p className="mt-5 max-w-md text-brown/70">Our first release keeps approved product and company answers clear. For technical approval, pricing, or account-specific help, ask Volt or connect with a person.</p></div><div className="space-y-3"><details className="faq-item"><summary>Which product family should I start with?</summary><p>Start with House wires for everyday building needs, Industrial cables for demanding projects, and Control & data for signal and smart-system connections.</p></details><details className="faq-item"><summary>Can Volt give me an official quotation?</summary><p>Volt can help you prepare the right request. A VOLTAMP specialist validates the final price, availability, taxes, freight, and technical fit.</p></details><details className="faq-item"><summary>How do I reach human support?</summary><p>Open Ask Volt and choose the human-support option, or start a quotation request from the page.</p></details></div></div></section>

        <section id="contact" className="section-space bg-cream"><div className="container grid gap-10 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><p className="eyebrow">Company & contact</p><h2>Good conversations make <span>good power.</span></h2><p className="mt-5 max-w-xl text-lg leading-8 text-brown/70">VOLTAMP ELEKTRIKALS PVT. LTD. is building a clearer, more human way to source electrical essentials from Ahmedabad, Gujarat, India. Approved certificates, awards, and team profiles will be published here as the content desk is activated.</p><div className="mt-8 grid gap-4 sm:grid-cols-3"><div className="mini-proof"><ShieldCheck /><strong>Certificates</strong><span>Approved documents coming soon</span></div><div className="mini-proof"><Sparkles /><strong>Our team</strong><span>Meet the people behind the power</span></div><div className="mini-proof"><Headphones /><strong>Contact</strong><span>Human help for your project</span></div></div></div><div className="contact-card"><p className="text-xs font-black uppercase tracking-[.15em] text-orange">Send an inquiry</p><h3 className="mt-2 font-display text-3xl font-black">Let’s talk shop.</h3><div className="mt-6 space-y-4"><Input aria-label="Your name" placeholder="Your name" className="rounded-2xl border-2 border-brown/10 bg-white" /><Input aria-label="Work email" type="email" placeholder="Work email" className="rounded-2xl border-2 border-brown/10 bg-white" /><Input aria-label="What are you powering" placeholder="What are you powering?" className="rounded-2xl border-2 border-brown/10 bg-white" /></div><Button onClick={handleQuote} className="mt-5 w-full rounded-full bg-orange py-6 font-black text-white hover:bg-orange/90">Send inquiry <ArrowRight className="ml-2 size-4" /></Button></div></div></section>

        <section id="quote" className="quote-section"><div className="container"><div className="quote-banner"><div><p className="eyebrow text-sun">Your project, our next bright idea</p><h2 className="text-white">Ready when<br /><span className="text-sun">you are.</span></h2></div><div className="quote-actions"><p>Tell us what you’re powering. We’ll help you find the right path forward.</p><Button onClick={handleQuote} className="rounded-full bg-sun px-6 py-6 font-black text-brown hover:bg-sun/90">Request a quote <ArrowRight className="ml-2" /></Button></div></div></div></section>
      </main>

      <footer className="bg-brown py-12 text-cream"><div className="container grid gap-10 md:grid-cols-[1.3fr_1fr_1fr_1fr]"><div><BrandMark compact={false} /><p className="mt-5 max-w-xs text-sm leading-6 text-cream/60">VOLTAMP ELEKTRIKALS PVT. LTD.<br />Ahmedabad, Gujarat, India</p></div><div><p className="footer-title">Explore</p><button onClick={() => jump("products")}>Products</button><button onClick={() => jump("about")}>About VOLTAMP</button><button onClick={() => jump("resources")}>Resources</button></div><div><p className="footer-title">Customers</p><button onClick={() => setAccountOpen(true)}>Customer portal</button><button onClick={handleQuote}>Request a quotation</button><button onClick={() => setChatOpen(true)}>Ask Volt</button></div><div><p className="footer-title">Employees</p><button onClick={() => setAccountOpen(true)}>Employee login</button><button onClick={() => setAccountOpen(true)}>Employee signup</button><p className="mt-4 text-xs leading-5 text-cream/45">Employee dashboards and internal tools arrive in a later phase.</p></div></div><div className="container mt-10 flex flex-wrap justify-between gap-3 border-t border-cream/15 pt-6 text-xs text-cream/45"><span>© 2026 VOLTAMP ELEKTRIKALS PVT. LTD.</span><span>Built for bright ideas.</span></div></footer>

      {mobileOpen && <div className="fixed inset-0 z-50 bg-brown/30 md:hidden"><div className="absolute right-0 top-0 h-full w-[86%] max-w-sm bg-cream p-6 shadow-2xl"><div className="flex items-center justify-between"><BrandMark compact /><button onClick={() => setMobileOpen(false)} aria-label="Close menu"><X /></button></div><div className="mt-12 flex flex-col gap-5 text-lg font-black">{nav.map((item) => <button key={item} className="text-left" onClick={() => jump(item === "Products" ? "products" : item === "About us" ? "about" : item === "Resources" ? "resources" : "calculator")}>{item}</button>)}<button className="mt-3 rounded-full bg-orange px-5 py-4 text-left text-white" onClick={() => { setMobileOpen(false); handleQuote(); }}>Request a quote <ArrowRight className="ml-2 inline size-5" /></button><button className="rounded-full border-2 border-brown px-5 py-4 text-left" onClick={() => { setMobileOpen(false); setAccountOpen(true); }}>Customer / employee access</button></div></div></div>}

      <Sheet open={chatOpen} onOpenChange={setChatOpen}><SheetContent className="w-full border-l-brown/10 bg-cream sm:max-w-xl"><SheetHeader><SheetTitle className="flex items-center gap-3 font-display text-2xl"><span className="calc-icon"><Sparkles className="size-5" /></span> Ask Volt</SheetTitle><p className="text-left text-sm text-brown/60">Product, quotation, and company questions. Human support is always one tap away.</p></SheetHeader><div className="mt-6"><AIChatBox messages={messages} onSendMessage={handleSend} isLoading={chatMutation.isPending} height="calc(100vh - 170px)" suggestedPrompts={["Which cable is right for a new home?", "I want to request a quotation", "Can I speak with a human?"]} /></div><button onClick={() => { setChatOpen(false); handleQuote(); }} className="mt-3 w-full rounded-full border-2 border-brown py-3 text-sm font-black"><Headphones className="mr-2 inline size-4" /> Escalate to human support</button></SheetContent></Sheet>

      {selectedDetail && <div className="fixed inset-0 z-50 flex items-center justify-center bg-brown/40 p-4"><div className="w-full max-w-lg rounded-[2rem] bg-cream p-7 shadow-2xl sm:p-9"><div className="flex items-start justify-between"><div><p className="eyebrow">Product detail</p><h2 className="mt-2 font-display text-3xl font-black">{selectedDetail.name}</h2></div><button onClick={() => setSelectedDetail(null)} aria-label="Close product details"><X /></button></div><ProductIllustration product={selectedDetail} /><p className="mt-6 text-brown/70">{selectedDetail.detail}</p><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-sun p-4"><span className="block text-xs font-bold uppercase tracking-wider">Starting point</span><strong className="mt-1 block font-display text-2xl">₹{selectedDetail.price}</strong></div><div className="rounded-2xl bg-white p-4"><span className="block text-xs font-bold uppercase tracking-wider">Best for</span><strong className="mt-1 block font-display text-lg">Project planning</strong></div></div><Button onClick={() => { setSelectedDetail(null); handleQuote(); }} className="mt-6 w-full rounded-full bg-brown py-6 font-black text-white">Request this product <Quote className="ml-2 size-4" /></Button></div></div>}

      {accountOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-brown/40 p-4"><div className="w-full max-w-lg rounded-[2rem] bg-cream p-7 shadow-2xl sm:p-9"><div className="flex items-start justify-between"><div><p className="eyebrow">Your VOLTAMP space</p><h2 className="mt-2 font-display text-3xl font-black">Welcome aboard.</h2></div><button onClick={() => setAccountOpen(false)} aria-label="Close account dialog"><X /></button></div><p className="mt-4 text-brown/65">Choose the doorway that fits you today. Secure account access is powered by VOLTAMP’s sign-in system.</p><div className="mt-7 grid gap-4 sm:grid-cols-2"><button onClick={() => { setAccountOpen(false); startLogin(); }} className="access-card"><UserRound /><strong>Customer access</strong><span>Sign in or create your customer profile</span><ArrowRight /></button><button onClick={() => { setAccountOpen(false); startLogin(); }} className="access-card access-employee"><Zap /><strong>Employee access</strong><span>Signup or login only for this phase</span><ArrowRight /></button></div>{user && <div className="mt-6 rounded-2xl bg-sun p-4 text-sm font-bold">Signed in as {user.name || user.email || "your VOLTAMP account"}. Your private portal modules will appear here as they are activated.</div>}</div></div>}
    </div>
  );
}
